spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction-shortened-url
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080